@APBDTut11_HostAddress = http://localhost:5205

POST {{APBDTut11_HostAddress}}/api/prescriptions
Content-Type: application/json

{
  "idDoctor": 1,
  "patient": {
    "idPatient": 1,
    "firstName": "John",
    "lastName": "Smith",
    "birthdate": "1990-01-01"
  },
  "medicaments": [
    {
      "idMedicament": 1,
      "dose": 10,
      "description": "Take after food"
    }
  ],
  "date": "2024-05-24",
  "dueDate": "2024-05-21"
}

###
